# -----------------------------
# instructions
# -----------------------------
# To convert a Whisper model generated by the "2-train-whisper" notebook:
# - see: /home/lucar/Development/chiara-speech2text_repo-private/rl-dpo/readme.md 
    
# To test locally:
# - Run Docker image which serves the Ollama LLM model:  /home/lucar/Development/chiara-speech2text_repo-private/models-mixer/launch-open-webui.sh
# - Run custom models-mixer which connects to Ollama:    python3 /home/lucar/Development/chiara-speech2text_repo-private/models-mixer/models-mixer.py
# - Run this file
# - Send requests:
# curl -F wav=@/home/lucar/Development/chiara-speech2text_repo-private/assets/audio_chiara-3.wav "http://127.0.0.1:8000/transcribe?upload_to_firebase_server=false"
# curl -F wav=@/home/lucar/Development/chiara-speech2text_repo-private/assets/audio_chiara-3.wav "http://127.0.0.1:8000/transcribe?upload_to_firebase_server=true"

# - To validate a transcript after the user confirms it:
#       curl -X POST -H "Content-Type: application/json" -H "X-Device-Id: dev" \
#       -d '{"transcript":"casa"}' \
#       "http://127.0.0.1:8000/validate"
#   OR see
#       /home/lucar/Development/chiara-speech2text_repo-private/rl-dpo/test_client_dpo.py

# Test LLM separately with:
'''
curl -X POST "127.0.0.1:8000/llm" \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      {
        "role": "user",
        "content": "why dogs bark?"
      }
    ]
  }'
'''
# -----------------------------


# -----------------------------
# imports
# -----------------------------
import argparse
import os
from fastapi.responses import JSONResponse, PlainTextResponse
from fastapi import FastAPI, UploadFile, File, Query, Request
from pydantic import BaseModel
import tempfile
import shutil
from faster_whisper import WhisperModel
import torch
import traceback
from datetime import datetime, timezone
import time
from concurrent.futures import ThreadPoolExecutor
import threading
import firebase_admin
from firebase_admin import credentials, storage
import requests
import os
import uvicorn
import uuid
from ollama import chat
from ollama import ChatResponse

import logging
# setup logging
#logging.basicConfig(level=logging.DEBUG)
logging.basicConfig(level=logging.INFO)
# -----------------------------



# -----------------------------
# environment variables
# -----------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Parse CLI arguments early so --env-file is available before any env loading.
_arg_parser = argparse.ArgumentParser(description="Chiara Speech-to-Text model server")
_arg_parser.add_argument(
    "--env-file",
    type=str,
    required=True,
    help="Path to the .env file to load environment variables from.",
)
_cli_args, _cli_unknown = _arg_parser.parse_known_args()

def _parse_env_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and ((value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")):
        value = value[1:-1]
    return value.encode("utf-8").decode("unicode_escape")


def _load_env_file(env_file: str) -> dict:
    env_file = os.path.abspath(env_file)
    if not os.path.isfile(env_file):
        return {}

    env_vars = {}
    with open(env_file, encoding="utf-8") as fh:
        for raw_line in fh:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            if key:
                env_vars[key] = _parse_env_value(value)
    return env_vars


def _resolve_credentials_env_file() -> str:
    return os.path.abspath(_cli_args.env_file)


def _apply_credentials_env_file() -> None:
    """Load .env file into os.environ (keys in the file win over existing values).

    Ensures MODEL_SERVER_PORT, FIREBASE_*, etc. work when running `python model-server.py`
    without shell `source` (which does not reliably export multiline values).
    """
    path = _resolve_credentials_env_file()
    loaded = _load_env_file(path)
    if loaded:
        logging.info(f"Loaded {len(loaded)} env vars from {path}")
    else:
        logging.warning(f"No env vars loaded from {path} (file missing or empty)")
    for key, value in loaded.items():
        if key:
            os.environ[key] = value


_apply_credentials_env_file()


def _env_str(name: str, *, fallback: str | None = None) -> str:
    value = (os.environ.get(name) or fallback or "").strip()
    return value


def _require_env_str(name: str, *, fallback: str | None = None) -> str:
    value = _env_str(name, fallback=fallback)
    if not value:
        env_file = _resolve_credentials_env_file()
        raise RuntimeError(f"Missing required env var {name} (set it in {env_file})")
    return value

# Read port from environment and ensure it's an int (fallback to 8000)
_http_port_env = os.environ.get("MODEL_SERVER_PORT")
try:                http_port = int(_http_port_env) if _http_port_env not in (None, "") else 8000
except Exception:   http_port = 8000     # if conversion fails, fall back to default port

path_whisper_finetuned = _require_env_str("MODEL_SERVER_WHISPER_MODEL_PATH")
firebase_storage_bucket = _require_env_str(
    "MODEL_SERVER_FIREBASE_BUCKET",
    fallback=os.environ.get("FIREBASE_CLIENT_STORAGE_BUCKET_DESTINATION"),
)
llm_model = _require_env_str("MODEL_SERVER_LLM_MODEL")
# -----------------------------


# -----------------------------
# user parameters
# -----------------------------
llm_prompt = '''
You are part of an Automatic Speech Recognition (ASR) system for a user who has dysarthria and impaired speech.
You have to do automated proofreading, and fix spelling and grammar of a given transcript.
- Do not propose multiple alternatives, only one final answer
- Your answer must only be the processed output, no decorations, no explanations (like "sure", "this is the answer", etc), only the final answer
- Do not change the meaning or add new information. Output ONLY the corrected text
- Remove any word repeated more than 3 times
- Add punctuation as needed
- Your input  is in Italian language
- Your output must be in Italian language    
'''

# DPO / Alternative transcript generation parameters
dpo_num_beams                           = 5                 # Number of beams for beam search
dpo_num_return_sequences                = 2                 # Number of alternative hypotheses to generate
dpo_sampling_temperatures               = [0.5, 0.8, 1.35]  # Temperatures for sampling diverse alternatives
dpo_sampling_attempts_per_temperature   = 2                 # Attempts per temperature to find diverse candidate

#
verbose                 = True

# Schema version for chiara-speech2text_scheme_data data stored in Firebase
SCHEMA_VERSION = "1.1.2_20260530"
# -----------------------------



# -----------------------------
# Validated data logging
# -----------------------------
validated_data_ttl_sec  = 120   # how long a cached transcription entry is valid for validation

# in-memory cache: device_key -> {ts, audio_file, duration, text, confidence, entry_id, ...}
LATEST_BY_DEVICE = {}
LATEST_BY_DEVICE_LOCK = threading.Lock()

# background executor for validation-triggered alternative computation
VALIDATION_EXECUTOR = ThreadPoolExecutor(max_workers=1)

# Interactions index (chiara-speech2text_scheme_data schema)
INTERACTIONS_INDEX_LOCK = threading.Lock()
# -----------------------------

# LLM request model
class LLMRequest(BaseModel):
    messages: list[dict]

#
class ValidateRequest(BaseModel):
    transcript: str


# -----------------------------
# set device (GPU or CPU)
# -----------------------------
# for warning: Found GPU0 NVIDIA GB10 which is of cuda capability 12.1,
# look into: https://build.nvidia.com/spark/pytorch-fine-tune/instructions
cuda_available = torch.cuda.is_available()
if cuda_available:
    logging.debug(f"CUDA device count: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        logging.debug(f"CUDA device {i} name: {torch.cuda.get_device_name(i)}")
device = "cuda" if cuda_available else "cpu"

logging.debug(f"PyTorch version: {torch.__version__}")
logging.debug(f"CUDA version from PyTorch: {torch.version.cuda}")
logging.debug(f"CUDA available according to PyTorch: {cuda_available}")
logging.info(f"Using device: {device}")

# Compute type for faster-whisper
compute_type = "float16" if cuda_available else "int8"
# -----------------------------


# -----------------------------
# initialize Firebase
# -----------------------------
_DEFAULT_FIREBASE_CREDENTIALS_PATH = os.path.join(_SCRIPT_DIR, "firebase_credentials.json")

def _resolve_firebase_credentials_path(path: str) -> str:
    if not path:
        return _DEFAULT_FIREBASE_CREDENTIALS_PATH
    if os.path.isabs(path):
        return path
    # Treat relative paths as relative to this script directory to be robust
    # when the server is started from a different working directory (e.g. systemd).
    return os.path.join(_SCRIPT_DIR, path)

def _normalize_env_private_key(private_key: str | None) -> str | None:
    if not private_key:
        return private_key
    return private_key.replace("\\n", "\n")

def _build_firebase_service_account_info(env_vars: dict) -> dict | None:
    """Build a Firebase service-account dict from FIREBASE_ADMIN_* vars."""
    project_id = (env_vars.get("FIREBASE_ADMIN_PROJECT_ID") or "").strip()
    if not project_id:
        return None

    private_key = _normalize_env_private_key(env_vars.get("FIREBASE_ADMIN_PRIVATE_KEY"))
    client_email = (env_vars.get("FIREBASE_ADMIN_CLIENT_EMAIL") or "").strip()
    if not private_key or not client_email:
        logging.warning(
            "FIREBASE_ADMIN_PROJECT_ID is set but FIREBASE_ADMIN_PRIVATE_KEY "
            "and/or FIREBASE_ADMIN_CLIENT_EMAIL are missing"
        )
        return None

    return {
        "type": env_vars.get("FIREBASE_ADMIN_TYPE", "service_account"),
        "project_id": project_id,
        "private_key_id": env_vars.get("FIREBASE_ADMIN_PRIVATE_KEY_ID"),
        "private_key": private_key,
        "client_email": client_email,
        "client_id": env_vars.get("FIREBASE_ADMIN_CLIENT_ID"),
        "auth_uri": env_vars.get("FIREBASE_ADMIN_AUTH_URI"),
        "token_uri": env_vars.get("FIREBASE_ADMIN_TOKEN_URI"),
        "auth_provider_x509_cert_url": env_vars.get("FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL"),
        "client_x509_cert_url": env_vars.get("FIREBASE_ADMIN_CLIENT_X509_CERT_URL"),
        "universe_domain": env_vars.get("FIREBASE_ADMIN_UNIVERSE_DOMAIN", "googleapis.com"),
    }

def _collect_firebase_env_vars() -> dict:
    """FIREBASE_* from os.environ (includes values applied from credentials/.env at startup)."""
    return {k: v for k, v in os.environ.items() if k.startswith("FIREBASE_")}

firebase_initialized = False
try:
    # Check if Firebase is already initialized
    firebase_admin.get_app()
    firebase_initialized = True
except ValueError:
    # Firebase not initialized yet
    cred = None
    firebase_env_vars = _collect_firebase_env_vars()
    service_account_info = _build_firebase_service_account_info(firebase_env_vars)
    if service_account_info:
        cred = credentials.Certificate(service_account_info)
        env_file = _resolve_credentials_env_file()
        logging.info(f"Firebase credentials loaded from env vars / {env_file}")
    else:
        firebase_credentials_path = _resolve_firebase_credentials_path(os.getenv("FIREBASE_CREDENTIALS_PATH", ""))
        if os.path.exists(firebase_credentials_path):
            cred = credentials.Certificate(firebase_credentials_path)
            logging.info(f"Firebase credentials loaded from file: {firebase_credentials_path}")
        else:
            env_file = _resolve_credentials_env_file()
            logging.warning(
                "Firebase credentials not found: set FIREBASE_ADMIN_* in "
                f"{env_file} (or export them), or provide a credentials file at {firebase_credentials_path}"
            )

    if cred is not None:
        firebase_admin.initialize_app(cred, {
            'storageBucket': firebase_storage_bucket
        })
        firebase_initialized = True
        logging.info(f"Firebase initialized successfully with bucket: {firebase_storage_bucket}")

# Get Firebase storage bucket
bucket = None
if firebase_initialized:
    try:
        bucket = storage.bucket()
        logging.info(f"Firebase storage bucket connected")
    except Exception as e:
        logging.warning(f"Could not connect to Firebase storage bucket: {e}")
else:
    logging.info("Firebase not initialized; skipping storage bucket connection")
# -----------------------------


# -----------------------------
# Firebase helper functions
# -----------------------------
def _get_next_file_index(folder_path):
    """Get the next available file index in Firebase folder."""
    try:
        if not bucket:
            return 1
        
        blobs = list(bucket.list_blobs(prefix=folder_path))
        # Extract numeric indices from .wav files
        indices = []
        for blob in blobs:
            if blob.name.endswith('.wav'):
                try:
                    # Extract the number from the filename
                    filename = os.path.basename(blob.name)
                    index = int(filename.replace('.wav', ''))
                    indices.append(index)
                except (ValueError, AttributeError):
                    continue
        
        if indices:
            return max(indices) + 1
        return 1
    except Exception as e:
        logging.warning(f"Could not get next file index: {e}")
        return 1

def _download_wav_from_firebase(folder: str, file_index: int, verbose: bool = False) -> str:
    """Download a wav from Firebase storage to a local tmp file and return its path."""
    if not bucket:
        raise RuntimeError("Firebase storage bucket not available")

    blob_path = f"{folder}/{int(file_index)}.wav"
    blob = bucket.blob(blob_path)
    if not blob.exists():
        raise RuntimeError(f"Firebase blob does not exist: {blob_path}")

    fd, tmp_path = tempfile.mkstemp(suffix=".wav")
    os.close(fd)
    try:
        blob.download_to_filename(tmp_path)
        if verbose:
            logging.info(f"[_download_wav_from_firebase] Downloaded {blob_path} to {tmp_path}")
        return tmp_path
    except Exception:
        try:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
        except Exception:
            pass
        raise

def _compute_and_upload_alternatives_in_background(device_key: str, folder: str, file_index: int, entry_id: str, winner_text: str, verbose: bool = False):
    """Background task: compute alternative hypotheses and update the Firebase interaction entry."""
    tmp_wav = None
    try:
        tmp_wav = _download_wav_from_firebase(folder, int(file_index), verbose=verbose)

        # Compute alternatives using the heavier path
        try:
            cand_winner, cand_winner_conf, alternatives = _transcribe_whisper_ct2(
                tmp_wav,
                model_whisper_finetuned,
                verbose=verbose,
                return_confidence=True,
                return_alternatives=True,
            )
        except Exception as e:
            logging.error(f"[validation-bg] Failed to compute alternatives: {e}")
            return

        # If alternatives is not empty, update the interaction entry
        if alternatives:
            updates = {
                "inference_alternative_transcript": alternatives,
            }
            _update_interaction(folder, entry_id, updates, verbose=verbose)
            if verbose:
                logging.info(f"[validation-bg] Updated interaction {entry_id} with {len(alternatives)} alternative(s)")

        # Optionally identify a loser transcript, but do not save it as a separate _l.txt file.
        loser_text = None
        if alternatives:
            for alt in alternatives:
                if (alt.get("text") or "").strip().lower() != (winner_text or "").strip().lower():
                    loser_text = alt.get("text")
                    break

        # Alternatives are persisted inside the Firebase interaction entry above.

    except Exception as e:
        tb = traceback.format_exc()
        logging.error(f"[validation-bg] Error computing alternatives for device_key={device_key}: {e}")
        logging.error(f"[validation-bg] Traceback:\n{tb}")
    finally:
        if tmp_wav:
            try:
                os.remove(tmp_wav)
            except Exception:
                pass

def _upload_to_firebase(audio_path, transcript, folder, verbose=False):
    """Upload audio and transcript to Firebase Storage."""
    try:
        if not bucket:
            logging.warning(f"Firebase storage bucket not available")
            return None, None
        
        # Get next file index
        file_index = _get_next_file_index(folder)
        
        # Upload audio file
        audio_blob_path = f"{folder}/{file_index}.wav"
        audio_blob = bucket.blob(audio_blob_path)
        audio_blob.upload_from_filename(audio_path)
        if verbose: logging.info(f"Uploaded audio to {audio_blob_path}")
        
        # Upload transcript file
        transcript_blob_path = f"{folder}/{file_index}.txt"
        transcript_blob = bucket.blob(transcript_blob_path)
        transcript_blob.upload_from_string(transcript.encode('utf-8'), content_type='text/plain; charset=utf-8')
        if verbose: logging.info(f"Uploaded transcript to {transcript_blob_path}")
        
        return folder, file_index
    
    except Exception as e:
        logging.error(f"Error uploading to Firebase: {e}")
        return None, None


# -----------------------------
# Interactions index (chiara-speech2text_scheme_data schema)
# -----------------------------
def _load_interactions_index(folder: str) -> list:
    """Load the interactions index JSON from Firebase, or return empty list."""
    try:
        if not bucket:
            return []
        blob_path = f"{folder}/data.json"
        blob = bucket.blob(blob_path)
        try:
            data = blob.download_as_bytes().decode("utf-8")
            import json
            parsed = json.loads(data)
            if isinstance(parsed, list):
                return parsed
            # If stored as dict with "data" key (with or without metadata)
            if isinstance(parsed, dict) and "data" in parsed:
                return parsed["data"]
            return []
        except Exception:
            return []
    except Exception as e:
        logging.warning(f"[_load_interactions_index] Failed to load index for folder {folder}: {e}")
        return []

def _save_interactions_index(folder: str, interactions: list, verbose: bool = False):
    """Save the interactions index JSON to Firebase with schema metadata."""
    import json
    try:
        if not bucket:
            logging.warning("[_save_interactions_index] Firebase bucket not available")
            return
        blob_path = f"{folder}/data.json"
        blob = bucket.blob(blob_path)
        payload = json.dumps({
            "schema_version": SCHEMA_VERSION,
            "data": interactions
        }, ensure_ascii=False, indent=2)
        blob.upload_from_string(payload.encode("utf-8"), content_type="application/json; charset=utf-8")
        if verbose:
            logging.info(f"[_save_interactions_index] Saved {len(interactions)} entries to {blob_path} (schema v{SCHEMA_VERSION})")
    except Exception as e:
        logging.error(f"[_save_interactions_index] Failed to save index for folder {folder}: {e}")

def _add_interaction(folder: str, entry: dict, verbose: bool = False):
    """Add a new interaction entry to the Firebase index (thread-safe)."""
    with INTERACTIONS_INDEX_LOCK:
        interactions = _load_interactions_index(folder)
        interactions.append(entry)
        _save_interactions_index(folder, interactions, verbose=verbose)
        if verbose:
            logging.info(f"[_add_interaction] Added entry {entry.get('entry_id')} to {folder}/data.json")

def _update_interaction(folder: str, entry_id: str, updates: dict, verbose: bool = False):
    """Update fields of an existing interaction entry by ID (thread-safe)."""
    with INTERACTIONS_INDEX_LOCK:
        interactions = _load_interactions_index(folder)
        for entry in interactions:
            if entry.get("entry_id") == entry_id:
                entry.update(updates)
                _save_interactions_index(folder, interactions, verbose=verbose)
                if verbose:
                    logging.info(f"[_update_interaction] Updated entry {entry_id} in {folder}/data.json")
                return
        logging.warning(f"[_update_interaction] Entry {entry_id} not found in {folder}/data.json")

def _build_entry_entry(entry_id: str, timestamp: str, audio_file: str,
                             audio_duration: float, transcript: str, confidence: float,
                             model_version: str, user_validated: bool = False,
                             alternatives: list = None, audio_source: str = "dgx") -> dict:
    """Build a chiara-speech2text_scheme_data-compliant entry dict."""
    # Validate audio_source is one of the allowed values
    if audio_source not in ("whatsapp", "frontend", "dgx"):
        audio_source = "dgx"
    
    entry = {
        "entry_id": entry_id,
        "entry_timestamp": timestamp,
        "audio_data": audio_file,
        "audio_source": audio_source,
        "audio_duration": round(audio_duration, 3),
        "inference_transcript": transcript,
        "inference_confidence": round(confidence, 2),
        "inference_model_version": model_version,
        "inference_alternative_transcript": alternatives or [],
        "user_validated": user_validated,
        "reviewer_is_reviewed": False,
        "reviewer_corrected_transcript": "",
    }
    return entry
# -----------------------------


# -----------------------------
# load models
# -----------------------------
def _looks_like_ct2_dir(path: str) -> bool:
    return (
        os.path.isdir(path)
        and os.path.exists(os.path.join(path, "model.bin"))
        and os.path.exists(os.path.join(path, "config.json"))
    )

def _looks_like_transformers_weights_dir(path: str) -> bool:
    if not os.path.isdir(path):
        return False
    weight_files = [
        "pytorch_model.bin",
        "model.safetensors",
        "tf_model.h5",
        "model.ckpt.index",
        "flax_model.msgpack",
    ]
    return any(os.path.exists(os.path.join(path, f)) for f in weight_files)

model_whisper_finetuned = None
model_whisper_finetuned_pt = None
processor_whisper_finetuned = None

try:
    # Prefer ct2 if the provided path already points to a ct2 directory.
    if _looks_like_ct2_dir(path_whisper_finetuned):
        from faster_whisper import WhisperModel

        logging.info(f"Loading ct2 model from: {path_whisper_finetuned}...")
        model_whisper_finetuned = WhisperModel(
            path_whisper_finetuned,
            device=device,
            compute_type=compute_type,
        )
        logging.info("Successfully loaded ct2 model")
    else:
        # If path is a local folder but doesn't contain transformer weights, skip the PyTorch attempt
        # to avoid confusing logs when the folder is actually a ct2 export.
        try_pytorch = True
        if os.path.isdir(path_whisper_finetuned) and not _looks_like_transformers_weights_dir(path_whisper_finetuned):
            try_pytorch = False

        if try_pytorch:
            from transformers import WhisperForConditionalGeneration, WhisperProcessor

            logging.info(f"Loading PyTorch model from: {path_whisper_finetuned}...")
            model_whisper_finetuned_pt = WhisperForConditionalGeneration.from_pretrained(path_whisper_finetuned)
            processor_whisper_finetuned = WhisperProcessor.from_pretrained(path_whisper_finetuned)
            model_whisper_finetuned_pt.to(device)
            model_whisper_finetuned = "pytorch_fallback"
            logging.info("Successfully loaded PyTorch model")

        # Fallback: try ct2 model next to the base path (common naming convention).
        if model_whisper_finetuned is None:
            logging.info("Attempting to load ct2 model as fallback...")

            ct2_candidates = []
            if path_whisper_finetuned.endswith("-ct2"):
                ct2_candidates.append(path_whisper_finetuned)
            ct2_candidates.append(path_whisper_finetuned + "-ct2")

            ct2_loaded = False
            for ct2_path in ct2_candidates:
                if not _looks_like_ct2_dir(ct2_path):
                    continue
                from faster_whisper import WhisperModel

                logging.info(f"Loading ct2 model from: {ct2_path}...")
                model_whisper_finetuned = WhisperModel(
                    ct2_path,
                    device=device,
                    compute_type=compute_type,
                )
                logging.info("Successfully loaded ct2 model")
                ct2_loaded = True
                break

            if not ct2_loaded:
                raise RuntimeError(
                    "Could not load Whisper model. "
                    f"Expected a Transformers weights directory at '{path_whisper_finetuned}' "
                    "or a CTranslate2 export directory containing 'model.bin' + 'config.json' at one of: "
                    + ", ".join(f"'{p}'" for p in ct2_candidates)
                )

except Exception as e:
    model_whisper_finetuned = None
    tb = traceback.format_exc()
    logging.error(f"Failed to load Whisper model: {e}")
    logging.error(f"Traceback:\n{tb}")
    logging.error(f"Exiting")
    exit(1)

# -----------------------------
# functions
# -----------------------------
def _process_wavfile(wav, verbose=False):
    # store received file for processing
    try:
        fd, wav_file = tempfile.mkstemp()
        os.close(fd)
        
        with open(wav_file, "wb") as buffer:
            shutil.copyfileobj(wav.file, buffer)
        
        if verbose: logging.info(f"[_process_input_wavfile] Received audio file. Converted '{wav.filename}' to '{wav_file}'. Now transcribing...")
        return wav_file
    
    except Exception as e:
        tb = traceback.format_exc()
        logging.error(f"[_process_input_wavfile] Error: {e}")
        logging.error(f"[_process_input_wavfile] Traceback:\n{tb}")

        # Attempt safe removal of temporary file
        try:
            if os.path.exists(wav_file):    os.remove(wav_file)
        except Exception as re:
            logging.warning(f"[_process_input_wavfile] Failed to remove tmp file {wav_file}: {re}")
            
        # raise exception
        raise e

def _transcribe_whisper_ct2(wav_file, model, verbose=False, return_confidence=False, return_alternatives=False):
    """Fast transcription path with optional alternative hypotheses.

    If return_confidence=True, returns (text, confidence_pct).
    If return_alternatives=True, also returns list of alternatives: [(text, confidence), ...]
    matching the scheme_data.json format: [{"text": "...", "confidence": 0.95}, ...]
    """
    start_time = time.time()

    logging.info(f"[_transcribe_whisper_ct2] model: {model}")
    logging.info(f"[_transcribe_whisper_ct2] verbose: {verbose}")
    logging.info(f"[_transcribe_whisper_ct2] return_confidence: {return_confidence}")
    logging.info(f"[_transcribe_whisper_ct2] return_alternatives: {return_alternatives}")

    try:
        if model is None:
            logging.error(f"[_transcribe_whisper_ct2] Whisper model not loaded")
            raise RuntimeError("Whisper model not loaded")

        import math

        winner_text = None
        winner_conf = 0.0
        alternatives = []

        # Handle PyTorch fallback
        if model == "pytorch_fallback":
            import librosa
            import torch

            waveform, sr = librosa.load(wav_file, sr=16000)
            inputs = processor_whisper_finetuned(waveform, sampling_rate=16000, return_tensors="pt")
            input_features = inputs.input_features.to(device)

            with torch.no_grad():
                outputs = model_whisper_finetuned_pt.generate(
                    input_features,
                    language="it",
                    task="transcribe",
                    num_beams=1,
                    num_return_sequences=1,
                    return_dict_in_generate=True,
                    output_scores=True,
                )

            decoded = processor_whisper_finetuned.batch_decode(outputs.sequences, skip_special_tokens=True)
            winner_text = (decoded[0] if decoded else "").strip()
            winner_conf = math.exp(outputs.sequences_scores[0].item()) * 100.0 if len(outputs.sequences_scores) > 0 else 0.0

            # Compute alternatives if requested
            if return_alternatives:
                try:
                    with torch.no_grad():
                        outputs_alt = model_whisper_finetuned_pt.generate(
                            input_features,
                            language="it",
                            task="transcribe",
                            num_beams=int(dpo_num_beams),
                            num_return_sequences=int(dpo_num_return_sequences),
                            return_dict_in_generate=True,
                            output_scores=True,
                        )

                    decoded_alt = processor_whisper_finetuned.batch_decode(outputs_alt.sequences, skip_special_tokens=True)
                    for txt, score in zip(decoded_alt, outputs_alt.sequences_scores):
                        alt_text = (txt or "").strip()
                        # Skip if same as winner or empty
                        if not alt_text or alt_text.lower() == winner_text.lower():
                            continue
                        alt_conf = math.exp(score.item()) * 100.0
                        alternatives.append({"text": alt_text, "confidence": round(alt_conf, 2)})
                        if len(alternatives) >= int(dpo_num_return_sequences) - 1:
                            break
                except Exception as e:
                    logging.warning(f"[_transcribe_whisper_ct2] Failed to compute alternatives: {e}")
        else:
            # faster-whisper path: first get best with beam_size=1
            segments, info = model.transcribe(
                wav_file,
                language="it",
                task="transcribe",
                beam_size=1,
                temperature=0.0,
                condition_on_previous_text=False,
            )
            segments_list = list(segments)
            winner_text = "".join([seg.text for seg in segments_list]).strip()
            if segments_list:
                avg_logprob = sum(seg.avg_logprob for seg in segments_list) / len(segments_list)
                winner_conf = math.exp(avg_logprob) * 100.0
            else:
                winner_conf = 0.0

            # Compute alternatives using temperature-based sampling if requested
            if return_alternatives:
                try:
                    sampled_candidates = []
                    for temp in dpo_sampling_temperatures:
                        for attempt in range(int(dpo_sampling_attempts_per_temperature)):
                            try:
                                segments_alt, _ = model.transcribe(
                                    wav_file,
                                    language="it",
                                    task="transcribe",
                                    beam_size=1,
                                    temperature=float(temp),
                                    condition_on_previous_text=False,
                                )
                                segments_alt_list = list(segments_alt)
                                alt_text = "".join([seg.text for seg in segments_alt_list]).strip()
                                
                                if alt_text:
                                    if segments_alt_list:
                                        avg_logprob = sum(seg.avg_logprob for seg in segments_alt_list) / len(segments_alt_list)
                                        alt_conf = math.exp(avg_logprob) * 100.0
                                    else:
                                        alt_conf = 0.0
                                    sampled_candidates.append((alt_text, alt_conf))
                            except Exception:
                                continue
                    
                    # Deduplicate and keep only alternatives different from winner
                    seen = {winner_text.lower()}
                    for alt_text, alt_conf in sampled_candidates:
                        norm_alt = alt_text.lower()
                        if norm_alt not in seen and alt_text.strip():
                            seen.add(norm_alt)
                            alternatives.append({"text": alt_text, "confidence": round(alt_conf, 2)})
                            if len(alternatives) >= int(dpo_num_return_sequences) - 1:
                                break
                except Exception as e:
                    logging.warning(f"[_transcribe_whisper_ct2] Failed to compute alternatives: {e}")

        end_time_whisper = time.time()
        if verbose:
            logging.info(f"[_transcribe_whisper_ct2] Whisper transcription took {end_time_whisper - start_time:.2f} seconds")
            logging.info(f"[_transcribe_whisper_ct2] Whisper transcript: {winner_text} (conf: {winner_conf:.1f}%)")
            if alternatives and verbose:
                for alt in alternatives:
                    logging.info(f"[_transcribe_whisper_ct2] Alternative:        {alt['text']} (conf: {alt['confidence']:.1f}%)")
            logging.info("")

        if return_alternatives:
            return (winner_text, winner_conf, alternatives) if return_confidence else (winner_text, alternatives)
        return (winner_text, winner_conf) if return_confidence else winner_text

    except Exception as e:
        tb = traceback.format_exc()
        logging.error(f"[_transcribe_whisper_ct2] Error during Whisper transcription: {e}")
        logging.error(f"[_transcribe_whisper_ct2] Traceback:\n{tb}")
        raise e

def _transcribe_whisper_ct2_pytorch(wav_file, verbose=False):
    """PyTorch fallback transcription."""
    import librosa
    import torch

    start_time = time.time()

    logging.info(f"[_transcribe_whisper_ct2_pytorch] model: {model}")
    logging.info(f"[_transcribe_whisper_ct2_pytorch] verbose: {verbose}")
    logging.info(f"[_transcribe_whisper_ct2_pytorch] return_confidence: {return_confidence}")
    logging.info(f"[_transcribe_whisper_ct2_pytorch] return_alternatives: {return_alternatives}")

    try:
        if verbose:
            logging.debug(f"[_transcribe_whisper_ct2_pytorch] Using PyTorch fallback")

        import math

        def _dedupe_candidates(cands):
            out = []
            seen_local = set()
            for txt, conf in cands:
                norm = (txt or "").strip()
                key = norm.lower()
                if not norm or key in seen_local:
                    continue
                seen_local.add(key)
                out.append((norm, conf))
            return out

        # Load audio
        waveform, sr = librosa.load(wav_file, sr=16000)

        # Process features
        inputs = processor_whisper_finetuned(waveform, sampling_rate=16000, return_tensors="pt")
        input_features = inputs.input_features.to(device)

        # Generate N-best candidates with beam search
        with torch.no_grad():
            _num_beams = int(dpo_num_beams)
            _num_return = int(dpo_num_return_sequences)
            outputs = model_whisper_finetuned_pt.generate(
                input_features,
                language="it",
                task="transcribe",
                num_beams=_num_beams,
                num_return_sequences=_num_return,
                return_dict_in_generate=True,
                output_scores=True,
            )

        sequences = outputs.sequences
        decoded = processor_whisper_finetuned.batch_decode(sequences, skip_special_tokens=True)
        
        candidates_raw = []
        for txt, score in zip(decoded, outputs.sequences_scores):
            conf = math.exp(score.item()) * 100.0
            candidates_raw.append((txt, conf))

        candidates = _dedupe_candidates(candidates_raw)

        if not candidates:
            raise RuntimeError("Whisper returned no transcription candidates")

        winner_text, winner_conf = candidates[0]
        loser_text, loser_conf = candidates[1] if len(candidates) > 1 else (None, 0.0)

        # Fallback: if beam search returns only one unique text, try sampling to get a distinct loser.
        if loser_text is None:
            sampled_raw = []
            with torch.no_grad():
                for t in dpo_sampling_temperatures:
                    for _ in range(int(dpo_sampling_attempts_per_temperature)):
                        try:
                            # Make sure sampling isn't accidentally deterministic across calls.
                            try:
                                torch.manual_seed(int(time.time() * 1000) % (2**31 - 1))
                            except Exception:
                                pass
                            out_s = model_whisper_finetuned_pt.generate(
                                input_features,
                                language="it",
                                task="transcribe",
                                do_sample=True,
                                temperature=float(t),
                                top_k=50,
                                top_p=0.95,
                                num_beams=1,
                                num_return_sequences=1,
                                return_dict_in_generate=True,
                                output_scores=True,
                            )
                            s_txt = processor_whisper_finetuned.batch_decode(out_s.sequences, skip_special_tokens=True)[0]
                            s_score = out_s.sequences_scores[0]
                            s_conf = math.exp(s_score.item()) * 100.0
                            sampled_raw.append((s_txt, s_conf))
                        except Exception as _e:
                            continue

            sampled_candidates = _dedupe_candidates(sampled_raw)
            for cand_txt, cand_conf in sampled_candidates:
                if cand_txt.strip().lower() != winner_text.strip().lower():
                    loser_text = cand_txt
                    loser_conf = cand_conf
                    break

        end_time_whisper = time.time()

        # info
        if verbose:
            logging.info(f"[_transcribe_whisper_ct2_pytorch] Whisper transcription took {end_time_whisper - start_time:.2f} seconds")

            # do not print this cause the winner was computed by the previous whisper run (before the validation)
            # here we just care about the loser            
            #logging.info(f"[_transcribe_whisper_ct2_pytorch] Whisper winner: {winner_text} (conf: {winner_conf:.1f}%)")
            
            if loser_text:
                logging.info(f"[_transcribe_whisper_ct2_pytorch] Whisper loser:  {loser_text} (conf: {loser_conf:.1f}%)")
                conf_gap = winner_conf - loser_conf
                logging.info(f"[_transcribe_whisper_ct2_pytorch] Confidence gap: {conf_gap:.1f}%")
                if conf_gap < 10.0:
                    logging.info(f"[_transcribe_whisper_ct2_pytorch] ALERT: Confidence gap < 10% (high-value sample)")
            else:
                logging.info(f"[_transcribe_whisper_ct2_pytorch] Whisper loser:  <none> (no distinct candidate)")
            logging.info("")

        # return
        return winner_text, winner_conf, loser_text, loser_conf

    except Exception as e:
        tb = traceback.format_exc()
        logging.error(f"[_transcribe_whisper_ct2_pytorch] Error during PyTorch transcription: {e}")
        logging.error(f"[_transcribe_whisper_ct2_pytorch] Traceback:\n{tb}")
        raise e

def _process_with_llm(transcript, verbose=False):
    start_time = time.time()

    prompt = llm_prompt + "The transcript is the following: " +transcript
    
    if verbose: logging.info(f"[_process_with_llm] prompt to LLM: {prompt}")
    #if verbose: logging.info(f"[_process_with_llm] Received: {transcript}")

    try:
        if verbose: logging.info(f"[_process_with_llm] Processing input with LLM...")

        # send the request to the model-server
        response: ChatResponse = chat(model=llm_model, messages=[
        {
            'role':     'user',
            'content':  prompt,
        },
        ])
        llm_response = response.message.content
        
        end_time_llm = time.time()

        # info
        if verbose:
            logging.info(f"[_process_with_llm] LLM response took {end_time_llm - start_time:.2f} seconds")
            logging.info(f"[_process_with_llm] LLM response: {llm_response}\n")
        
        # return
        return llm_response
    
    except Exception as e:
        logging.error(f"[_process_with_llm] Error during LLM response: {e}")
        raise e
# -----------------------------


# -----------------------------
# app
# -----------------------------
app = FastAPI()

# greet
@app.get("/")
def greet_json():
    return {
        "msg"   : "Hello world. Welcome to chiara-speech2text model-server",
        "usage" : "POST a WAV file to /transcribe for speech transcription, or POST a JSON chat payload to /llm for language-model processing",
    }

# return model version
@app.get("/get_model_version")
def get_model_version():
    return PlainTextResponse(content=path_whisper_finetuned)

# transcribe
@app.post('/transcribe')
def transcribe(
    wav:                        UploadFile = File(...),
    folder:                     str = Query(None),  # Optional folder name from recorder
    word:                       str = Query(None),  # Optional word being recorded
    index:                      int = Query(None),  # Optional index in recording session
    audio_source:               str = Query("dgx"),  # Source of audio (dgx, frontend, whatsapp)
    upload_to_firebase_server:  bool = Query(True),
    process_with_llm:           bool = Query(False),
    return_alternatives:        bool = Query(False),
    json_response:              bool = Query(False),
    request:                    Request = None,
):
    logging.info(f"[transcribe] Received request. Processing...")
    logging.info(f"[transcribe] folder: {folder}")
    logging.info(f"[transcribe] word: {word}")
    logging.info(f"[transcribe] index: {index}")
    logging.info(f"[transcribe] audio_source: {audio_source}")
    logging.info(f"[transcribe] upload_to_firebase_server: {upload_to_firebase_server}")
    logging.info(f"[transcribe] process_with_llm: {process_with_llm}")
    logging.info(f"[transcribe] return_alternatives: {return_alternatives}")
    logging.info(f"[transcribe] json_response: {json_response}")

    start_time = time.time()    
  
    # transcribe with Whisper model
    try:
        # process input wav file
        wav_file = _process_wavfile(wav)

        if return_alternatives:
            transcript_whisper, whisper_conf, alternatives = _transcribe_whisper_ct2(
                wav_file,
                model_whisper_finetuned,
                verbose=verbose,
                return_confidence=True,
                return_alternatives=True,
            )
        else:
            transcript_whisper, whisper_conf = _transcribe_whisper_ct2(
                wav_file,
                model_whisper_finetuned,
                verbose=verbose,
                return_confidence=True,
                return_alternatives=False,
            )
            alternatives = []

        transcript = transcript_whisper
    except Exception as e:
        tb = traceback.format_exc()
        logging.error(f"[transcribe] Error during transcription: {e}")
        logging.error(f"[transcribe] Traceback:\n{tb}")
        return JSONResponse(content={"error": str(e), "traceback": tb}, status_code=500)

    # process with LLM
    llm_available = False
    try:
        if process_with_llm:
            logging.info(f"[transcribe] Calling LLM...")
            if llm_response := _process_with_llm(transcript, verbose=verbose):
                transcript = llm_response
                llm_available = True
            else:
                logging.warning("[transcribe] LLM response is empty. Keeping original transcript.")
    except Exception as e:
        tb = traceback.format_exc()
        logging.error(f"[transcribe] Error during LLM processing: {e}")
        logging.error(f"[transcribe] Traceback:\n{tb}")

    # finalize
    end_time = time.time()
    if verbose:
        logging.info(f"[transcribe] Total required time: {end_time - start_time:.2f} seconds")
        logging.info(f"[transcribe] Final transcript: {transcript}")

    # store received audio to Firebase Storage
    firebase_audio_file = None
    entry_id = None
    if upload_to_firebase_server:
        # Use provided folder name or generate default
        if folder:
            firebase_folder = folder
        elif llm_available:
            firebase_folder = f"{datetime.now().strftime('%Y%m%d')}_dgx-whisper-llm"
        else:
            firebase_folder = f"{datetime.now().strftime('%Y%m%d')}_dgx-whisper"
        
        folder_result, file_index = _upload_to_firebase(wav_file, transcript, firebase_folder, verbose=verbose)

        # Cache metadata for later validation.
        if folder_result and file_index:
            firebase_audio_file = f"{folder_result}/{file_index}.wav"
            device_key = None
            try:
                device_key = request.headers.get("X-Device-Id") if request else None
            except Exception:
                device_key = None
            if not device_key:
                try:
                    device_key = request.client.host if request and request.client else "unknown"
                except Exception:
                    device_key = "unknown"

            # Compute audio duration
            try:
                import wave
                with wave.open(wav_file, 'rb') as wf:
                    audio_duration = wf.getnframes() / wf.getframerate()
            except Exception:
                audio_duration = 0.0

            # Generate unique interaction ID and timestamp
            entry_id = str(uuid.uuid4())
            entry_timestamp = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

            # Set model version in the interaction entry. If LLM processing was applied, append the LLM model name to the base Whisper model version for clarity.
            model_version = path_whisper_finetuned
            if llm_available:
                model_version = path_whisper_finetuned + " + " + llm_model

            # Create chiara-speech2text_scheme_data entry (user_validated=False initially)
            entry_entry = _build_entry_entry(
                entry_id=entry_id,
                timestamp=entry_timestamp,
                audio_file=f"{file_index}.wav",
                audio_duration=audio_duration,
                transcript=(transcript or "").strip(),
                confidence=whisper_conf,
                model_version=model_version,
                user_validated=False,
                alternatives=alternatives,
                audio_source=audio_source,  # Pass the audio source
            )
            _add_interaction(folder_result, entry_entry, verbose=verbose)

            with LATEST_BY_DEVICE_LOCK:
                LATEST_BY_DEVICE[device_key] = {
                    "ts":           time.time(),
                    "folder":       firebase_folder,
                    "audio_file":   firebase_audio_file,
                    "duration":     audio_duration,
                    "text":         (transcript or "").strip(),
                    "confidence":   whisper_conf,
                    "entry_id": entry_id,
                    "alternatives":  alternatives,
                }
            if verbose:
                logging.info(
                    f"[transcribe] Cached validation entry for device_key={device_key} audio_file={firebase_audio_file} entry_id={entry_id}"
                )
        else:
            if verbose:
                logging.info("[transcribe] Firebase upload failed; skipping validation cache")
    else:
        if verbose: logging.info(f"[transcribe] Skipping upload to Firebase as per request parameter")

    # remove audio file
    try:                os.remove(wav_file)
    except Exception:   pass

    # prepare response payload
    response_payload = {
        "transcript": transcript,
        "whisper_confidence": round(whisper_conf, 2),
        "whisper_model": path_whisper_finetuned,
        "alternatives": alternatives if return_alternatives else [],
        "entry_id": entry_id,
        "status": "success",
    }

    # return json response
    if json_response: return JSONResponse(content=response_payload)
    
    # default: return plain text when json_response is False
    return PlainTextResponse(content=transcript)

# validate endpoint
@app.post("/validate")
def validate(request_body: ValidateRequest, request: Request):
    device_key = None
    try:
        device_key = request.headers.get("X-Device-Id")
    except Exception:
        device_key = None
    if not device_key:
        try:
            device_key = request.client.host if request.client else "unknown"
        except Exception:
            device_key = "unknown"

    with LATEST_BY_DEVICE_LOCK:
        entry = LATEST_BY_DEVICE.get(device_key)
    now = time.time()
    if not entry:
        logging.info(f"[validate] No pending entry for device_key={device_key}")
        return JSONResponse(content={"status": "noop", "reason": "no_pending"}, status_code=200)

    age = now - float(entry.get("ts", 0.0))
    if age > float(validated_data_ttl_sec):
        logging.info(f"[validate] Stale validation for device_key={device_key} age_sec={age:.1f}; ignoring")
        with LATEST_BY_DEVICE_LOCK:
            try:
                del LATEST_BY_DEVICE[device_key]
            except KeyError:
                pass
        return JSONResponse(content={"status": "noop", "reason": "stale"}, status_code=200)

    received = (request_body.transcript or "").strip().lower()
    expected = (entry.get("text") or "").strip().lower()
    logging.info(f"[validate] Received: {received}")
    logging.info(f"[validate] Expected: {expected}")
    if received != expected:
        logging.info(f"[validate] Transcript mismatch for device_key={device_key}; ignoring")
        return JSONResponse(content={"status": "noop", "reason": "mismatch"}, status_code=200)

    # Extract audio file index (needed for background processing)
    audio_file = entry.get("audio_file")
    file_index = None
    try:
        if audio_file:
            file_index = int(os.path.splitext(os.path.basename(audio_file))[0])
    except Exception:
        file_index = None

    # Remove the entry immediately (idempotent validation).
    with LATEST_BY_DEVICE_LOCK:
        try:
            del LATEST_BY_DEVICE[device_key]
        except KeyError:
            pass

    # Mark interaction as user_validated=true in data.json
    entry_id = entry.get("entry_id")
    folder = entry.get("folder", "")
    if entry_id and folder:
        updates = {"user_validated": True}

        # If alternatives were computed and cached during transcription (unlikely now), add them.
        cached_alternatives = entry.get("alternatives", []) or []
        if cached_alternatives:
            updates["inference_alternative_transcript"] = cached_alternatives
            if verbose:
                logging.info(f"[validate] Adding {len(cached_alternatives)} cached alternative(s) to interaction {entry_id}")

        _update_interaction(folder, entry_id, updates, verbose=verbose)
        logging.info(f"[validate] Marked interaction {entry_id} as user_validated in {folder}/data.json")

        # If no alternatives available yet, queue background computation (won't block response)
        if not cached_alternatives and file_index is not None:
            try:
                VALIDATION_EXECUTOR.submit(
                    _compute_and_upload_alternatives_in_background,
                    device_key,
                    folder,
                    int(file_index),
                    entry_id,
                    (entry.get("text") or "").strip(),
                    verbose,
                )
                logging.info(f"[validate] Queued background alternative computation for {folder}/{file_index} interaction {entry_id}")
                return JSONResponse(content={"status": "ok", "queued": True}, status_code=200)
            except Exception as e:
                logging.error(f"[validate] Failed to queue background job: {e}")
                return JSONResponse(content={"status": "error", "reason": "queue_failed"}, status_code=500)

    logging.info(f"[validate] Validation complete for device_key={device_key} audio_file={entry.get('audio_file')}")
    return JSONResponse(content={"status": "ok"}, status_code=200)

# llm endpoint
@app.post('/llm')
def process_llm(request: LLMRequest):
    start_time = time.time()
    
    try:
        if verbose:
            logging.info(f"[/llm] Processing request with model: {llm_model}")
            logging.info(f"[/llm] Received messages: {request.messages}")
        
        # send the request to the ollama model
        response: ChatResponse = chat(model=llm_model, messages=request.messages)
        llm_response = response.message.content
        
        end_time = time.time()
        
        # info
        if verbose:
            logging.info(f"[/llm] LLM response took {end_time - start_time:.2f} seconds")
            logging.info(f"[/llm] Response: {llm_response}")
        
        # return
        return PlainTextResponse(content=llm_response)
    
    except Exception as e:
        logging.error(f"[/llm] Error: {e}")
        return JSONResponse(content={"error": str(e)}, status_code=500)

#
if __name__ == "__main__":
    print(f"\n\n\n--------------------------------------------------------------------------")
    print(f"                      Hello world. I'm model-server-dgx")
    print(f"\nTrack changes:")
    print(f"- v20260519: added chiara-speech2text_scheme_data index (data.json) per Firebase folder")
    print(f"- v20260513: migrated to faster-whisper (was transformers/PyTorch), added info about user-validation")
    print(f"- v20260419: added endpoint for LLM")
    print(f"- v20260409: use ollama python SDK instead of sending HTTP requests to separate ollama-based server")
    print(f"- v20260320: warmup ASRs and LLM at startup to reduce latency of first request")
    print(f"- v7: added parameter to choose whether to upload files to Firebase Storage")
    print(f"- v6: added spell checking via LLM")
    print(f"- v5: added canary vanilla model")
    print(f"- v4: added whisper vanilla model")
    print(f"- v3: mixture of models")
    print(f"- v2: store received files to Firebase Storage")
    print(f"- v1: 1st release")
    print(f"--------------------------------------------------------------------------\n\n\n")
    
    # print
    logging.info(f"Starting ASR server with the following configuration:")
    logging.info(f"- HTTP port: {http_port}")
    logging.info(f"- Whisper finetuned model path: {path_whisper_finetuned}")
    logging.info(f"- LLM model: {llm_model}")
    logging.info(f"- Interactions index: stored as {{firebase_folder}}/data.json in Firebase bucket")
    logging.info(f"- Validation TTL (sec): {validated_data_ttl_sec}")
    
    # warm up ASR model to reduce latency of first request
    wav_file = "/home/lucar/Development/chiara-speech2text_repo-private/assets/audio_chiara-1.wav"
    logging.info(f"Trying to warm-up ASR model (up to 5 iterations)...")
    try:
        for i in range(5):
            logging.info(f"[ASR warm-up] Iteration {i + 1}/5...")
            transcript_whisper = _transcribe_whisper_ct2(
                wav_file,
                model_whisper_finetuned,
                verbose=True,
            )
            logging.info(f"Warm-up transcript (whisper finetuned): {transcript_whisper}")
            break
        logging.info(f"ASR models warmed up successfully")
    except Exception as e:
        tb = traceback.format_exc()
        logging.warning(f"[ASR warm-up] Error during ASR warm-up: {e}")
        logging.warning(f"[ASR warm-up] Traceback:\n{tb}")
        logging.warning(f"[ASR warm-up] Proceeding with app startup despite warm-up failure")

    # warm up LLM (up to 5 times, exits on first success)
    '''
    logging.info(f"Setting LLM model: {llm_model}")
    logging.info(f"Trying to warm-up LLM (up to 5 iterations)...") 
    try:
        for i in range(5):
            logging.info(f"[LLM warm-up] Iteration {i + 1}/5...")
            transcript_llm = _process_with_llm(transcript_whisper, verbose=True)
            logging.info(f"[LLM warm-up] Iteration {i + 1} transcript: {transcript_llm}")
            logging.info(f"[LLM warm-up] Successfully warmed up on iteration {i + 1}, exiting loop")
            break
        logging.info(f"LLM warmed up successfully")
    except Exception as e:
        tb = traceback.format_exc()
        logging.warning(f"[LLM warm-up] Error during LLM warm-up: {e}")
        logging.warning(f"[LLM warm-up] Traceback:\n{tb}")
        logging.warning(f"[LLM warm-up] Proceeding with app startup despite warm-up failure")
    '''
    # run app
    uvicorn.run(app, host="0.0.0.0", port=http_port)
# -----------------------------